<a href="https://colab.research.google.com/github/UMAIR000001/PyTorch-Week4/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
# 1. Install Git (if needed)
!apt-get install git

# 2. Set your Git username & email (only once)
!git config --global user.email "umairhafeez951@gmail.com"
!git config --global user.name "UMAIR000001"

# 3. Clone your GitHub repo to Colab
!git clone https://github.com/UMAIR000001/PyTorch-Week4.git


'apt-get' is not recognized as an internal or external command,
operable program or batch file.


fatal: destination path 'PyTorch-Week4' already exists and is not an empty directory.


In [35]:
print("first day of learning Pytorch")

first day of learning Pytorch


In [36]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.7.1+cpu


##  Introduction To Tensors
### Creating Tensors

In [37]:
#scalar
scalar =torch.tensor(5366)
scalar

tensor(5366)

In [38]:
# Check the number of dimensions of vector
scalar.ndim

0

In [39]:
# Get tensor back as python int
scalar.item()

5366

In [40]:
#Vector
vector=torch.tensor([1,2,3,4,5])
vector

tensor([1, 2, 3, 4, 5])

In [41]:
# Check the number of dimensions of vector
vector.ndim

1

In [42]:
# Another important concept for tensors is their shape attribute. The shape tells you how the elements inside them are arranged.
vector.shape

torch.Size([5])

In [43]:
#MATRIX
MATRIX=torch.tensor([[1,2],[3,4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [44]:
MATRIX.ndim

2

In [45]:
MATRIX[0]

tensor([1, 2])

In [46]:
MATRIX.shape

torch.Size([2, 2])

In [47]:
#TENSOR
TENSOR=torch.tensor([[[1,1,1],[2,2,2]]])
TENSOR

tensor([[[1, 1, 1],
         [2, 2, 2]]])

In [48]:
TENSOR.ndim

3

In [49]:
TENSOR.shape

torch.Size([1, 2, 3])

# Randon tensors
A random tensor is a multi-dimensional array filled with randomly generated values, created using PyTorch functions like torch.rand(), torch.randn(), or torch.randint().

->These tensors are often used to:

->Simulate input data

->Initialize weights of neural networks

->Test models before using real data

##Different Random Tensor Functions

1:
Function    |	Range of Values             |Data Type
torch.rand()|	Uniform random values [0, 1)|float32 


##❓Why are random tensors so valuable in deep learning?
In deep learning, we start with random numbers (random tensors) to initialize model parameters (like weights).
Then the model:

🔁 Looks at data → compares predictions to real values

🔁 Updates the random numbers (weights) using gradients

🔁 Repeats this process until the model learns to make accurate predictions. 


## 💡 Why Use Random Tensors Instead of Zero?
If all weights were zero, the model would learn nothing unique (all neurons behave the same).
Randomness breaks symmetry, allowing each neuron to learn something different.

In [50]:
 # Create a random tensor of size (5,2)
#random_tensor=torch.rand(size=(5,3)) == random_tensor=torch.rand(5,3)
random_tensor=torch.rand(size=(5,3))
random_tensor,random_tensor.dtype


(tensor([[0.3043, 0.5250, 0.4961],
         [0.9479, 0.5363, 0.5138],
         [0.7729, 0.2863, 0.3759],
         [0.7773, 0.9608, 0.5168],
         [0.1351, 0.3059, 0.5545]]),
 torch.float32)

The flexibility of `torch.rand()` is that we can adjust the `size` to be whatever we want.

For example, say you wanted a random tensor in the common image shape of `[224, 224, 3]` (`[height, width, color_channels`]).
##🧠 Key Point to Remember: 
In image processing:

A color image is usually a 3D tensor → height × width × channels

A batch of images becomes a 4D tensor → batch_size × height × width × channels

In [51]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(224, 224, 3)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [52]:
# Summary of all task of  random tensor  
demo_tensor=torch.rand(size=(2,5))
demo_tensor,demo_tensor.dtype, demo_tensor.shape,demo_tensor.ndim

(tensor([[0.1260, 0.0607, 0.2714, 0.9058, 0.6279],
         [0.9163, 0.9493, 0.5272, 0.3357, 0.5496]]),
 torch.float32,
 torch.Size([2, 5]),
 2)

# Zeros and Ones

In [53]:
#Creating a tensor all of zeros
# probably used in most cases
zeros_tensor=torch.zeros(2,5)
#Multiplication of Zeros tensor to a random tensor
zeros_tensor*demo_tensor 
#zeros_tensor,zeros_tensor.dtype,zeros_tensor.shape,zeros_tensor.ndim

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [54]:
#Creating a tensor all of ones
ones_tensor=torch.ones(2,5)
#Multiplication of Ones tensor to a random tensor
ones_tensor*demo_tensor 
#ones_tensor,zeros_tensor.dtype,zeros_tensor.shape,zeros_tensor.ndim

tensor([[0.1260, 0.0607, 0.2714, 0.9058, 0.6279],
        [0.9163, 0.9493, 0.5272, 0.3357, 0.5496]])

#16. Creating a range of tensors and tensors-like

In [55]:
# Use torch.arange()
one_to_ten=torch.arange(start=1,end=11,step=1)
one_to_ten


tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
zero_to_twenties=torch.arange(start=0,end=21,step=2)
zero_to_twenties

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [57]:
#Creating tensors like for ones
one_to_ten_like=torch.ones_like(input=one_to_ten)
one_to_ten_like


tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [58]:
#Creating tensors like for zeros
one_to_ten_like=torch.zeros_like(input=one_to_ten)
one_to_ten_like


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [59]:
# Creating tensors like for random tensors here typecasting is required 
demo=torch.rand_like(input=one_to_ten,dtype=torch.float32)
demo

tensor([0.1384, 0.8547, 0.9733, 0.9501, 0.0862, 0.7271, 0.4028, 0.4749, 0.2270,
        0.0702])

# 17 Dealing With tensor datatypes

In [60]:
# Default Datatype for tensors is float32 for float values 

float_32_tensor=torch.tensor((1.0,2.0,3.0),
                              dtype=None,
                              device=None,
                              requires_grad=False)
float_32_tensor.dtype,float_32_tensor.device,float_32_tensor.requires_grad,float_32_tensor.shape,float_32_tensor.ndim,float_32_tensor

(torch.float32,
 device(type='cpu'),
 False,
 torch.Size([3]),
 1,
 tensor([1., 2., 3.]))

In [61]:
float_32_tensor=torch.tensor([1,2],
                             dtype=torch.float32,
                             device=None,
                             requires_grad=False)
float_32_tensor.dtype

torch.float32